name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (FastAPI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Import smoke test
        run: |
          python - <<'PY'
          import cv2, PIL, fastapi, numpy
          import importlib
          importlib.import_module('backend.app')
          print('Imports OK')
          PY

      - name: Start server and health check
        run: |
          nohup uvicorn backend.app:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid
          sleep 3
          curl -fsS http://127.0.0.1:8000/api/health | grep '"ok"'
        shell: bash

      - name: Stop server
        if: always()
        run: |
          kill $(cat uvicorn.pid) || true
        shell: bash

  frontend:
    name: Frontend (Vite build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
